apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "jupyter-web-app.labels" . | nindent 4 }}
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "jupyter-web-app.name" . }}-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jupyter-web-app.name" . }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ include "jupyter-web-app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}