apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    {{- include "jupyter-web-app.labels" . | nindent 4 }}
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "jupyter-web-app.name" . }}-web-app-notebook-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "jupyter-web-app.name" . }}-web-app-notebook-role
subjects:
- kind: ServiceAccount
  name: {{ include "jupyter-web-app.serviceAccountName" . }}