apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "notebook-controller.labels" . | nindent 4 }}
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "notebook-controller.name" . }}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "notebook-controller.name" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "notebook-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}