apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "notebook-controller.labels" . | nindent 4 }}
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "notebook-controller.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
  selector:
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}