apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-authservice-parameters
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "oidc-authservice.selectorLabels" . | nindent 4 }}
data:
  {{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
  {{- end }}