apiVersion: v1
kind: Service
metadata:
  name:  {{ include "oidc-authservice.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "oidc-authservice.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    name: http-authservice
    targetPort: http-api
  publishNotReadyAddresses: true
