apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "profiles.name" . }}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "profiles.name" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "profiles.serviceAccountName" . }}