apiVersion: v1
kind: Service
metadata:
  name: {{ include "profiles.fullname" . }}
  labels:
    {{- include "profiles.labels" . | nindent 4 }}
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}