apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "volumes-web-app.labels" . | nindent 4 }}
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "volumes-web-app.fullname" . }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- with .Values.appLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "volumes-web-app.labels" . | nindent 8 }}
        {{- with .Values.appLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - env:
        - name: APP_PREFIX
          value: {{ .Values.deployment.env.APP_PREFIX }}
        - name: APP_SECURE_COOKIES
          value: {{ .Values.deployment.env.APP_SECURE_COOKIES | quote }}
        - name: USERID_HEADER
          value: {{ .Values.deployment.env.USERID_HEADER }}
        - name: USERID_PREFIX
          value: {{ .Values.deployment.env.USERID_HEADER | quote }} 
        image: {{ .Values.deployment.image }}
        name: {{ include "volumes-web-app.name" . }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
      serviceAccountName: {{ include "volumes-web-app.serviceAccountName" . }}