apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "volumes-web-app.labels" . | nindent 4 }}
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "volumes-web-app.fullname" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.deployment.containerPort }}
  selector:
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  type: ClusterIP