apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ .Values.envoyFilter.name }}
spec:
  workloadSelector:
    {{- with .Values.envoyFilter.workloadSelector.labels }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: "envoy.filters.http.ext_authz"
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            http_service:
              server_uri:
                uri: http://{{ include "oidc-authservice.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
                cluster: outbound|{{ .Values.service.port }}||{{ include "oidc-authservice.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
                timeout: 10s
              authorization_request:
                allowed_headers:
                  patterns:
                    - exact: "authorization"
                    - exact: "cookie"
                    - exact: "x-auth-token"
              authorization_response:
                allowed_upstream_headers:
                  patterns:
                    - exact: "kubeflow-userid"
