{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
   name: {{ .Values.secretProviderClass.name }}
   namespace: {{ .Release.Namespace | quote }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  secretObjects:
    - secretName: {{ .Values.secretProviderClass.name }}
      type: Opaque
      data:
        - objectName: clientid
          key: CLIENT_ID
        - objectName: clientsecret
          key: CLIENT_SECRET
  parameters:
    objects: |
      - objectName: {{ .Values.secretProviderClass.awsSecretName | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: CLIENT_ID
            objectAlias: clientid
          - path: CLIENT_SECRET
            objectAlias: clientsecret
{{- end }}