apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    {{- with .Values.ui.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "kubeflow-pipelines.name" . }}-ui
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - kubeflow.org
  resources:
  - viewers
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - listapiVersion: rbac.authorization.k8s.io/v1
---
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    {{- with .Values.ui.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "kubeflow-pipelines.name" . }}-ui
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - kubeflow.org
  resources:
  - viewers
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list