apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    {{- with .Values.ui.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "kubeflow-pipelines.name" . }}-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubeflow-pipelines.name" . }}-ui
subjects:
- kind: ServiceAccount
  name: {{ .Values.ui.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}