apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "admission-webhook.labels" . | nindent 4 }}
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: "true"
  name: {{ include "admission-webhook.fullname" . }}-poddefaults-admin
rules: []
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.kubeflow.org/aggregate-to-kubeflow-poddefaults-admin: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "admission-webhook.labels" . | nindent 4 }}
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
  name: {{ include "admission-webhook.fullname" . }}-poddefaults-edit
rules: []
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.kubeflow.org/aggregate-to-kubeflow-poddefaults-edit: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "admission-webhook.labels" . | nindent 4 }}
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-poddefaults-admin: "true"
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-poddefaults-edit: "true"
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: "true"
  name: {{ include "admission-webhook.fullname" . }}-poddefaults-view
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - poddefaults
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "admission-webhook.labels" . | nindent 4 }}
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "admission-webhook.fullname" . }}-cluster-role
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - poddefaults
  verbs:
  - get
  - watch
  - list
  - update
  - create
  - patch
  - delete