apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "admission-webhook.name" . }}-cert
  labels:
    {{- include "admission-webhook.labels" . | nindent 4 }}
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "admission-webhook.name" . }}-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: ""
    service:
      name: {{ include "admission-webhook.name" . }}
      namespace: {{ .Release.Namespace }}
      path: {{ .Values.mutatingWebhookConfig.path }}
  name: {{ include "admission-webhook.name" . }}.kubeflow.org
  namespaceSelector:
    matchLabels:
      app.kubernetes.io/part-of: kubeflow-profile
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods