apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "admission-webhook.labels" . | nindent 4 }}
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "admission-webhook.name" . }}
spec:
  ports:
  - name: https-webhook
    port: {{ .Values.service.port }}
    targetPort: https-webhook
  selector:
    {{- with .Values.appLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}